name = input ("enter name: ")
print (name)
age = input ("enter age: ")
print (age)
university = input ("enter University name: ")
print (university)
id = input ("enter id number: ")
print (id)
address = input ("enter address: ")
print (address)
phone = input ("enter phone number: ")
print (phone)
ip = input ("enter ip address: ")
print (ip)
card = input ("enter credit card numbers: ")
print (card)
